#spring:
#  mail:
#    host: localhost
#    port: 25

#JWT config
jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration: 1800000
    refresh-expiration: 604800000

#Email config
email:
  from: no-reply@app.com