#spring:
#  mail:
#    host: localhost
#    port: 25

#JWT config
jwt:
  secret: JWT_SECRET
  issuer: JWT_ISSUER
  token:
    access-expiration: 1800
    refresh-expiration: 604800

#Email config
email:
  from: no-reply@app.com