#spring:
#  mail:
#    host: localhost
#    port: 25

#JWT config
jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}

#Email config
email:
  from: no-reply@app.com