spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: root
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
        #highlight_sql: true
        #format_sql: true
        #show_sql: true
        #use_sql_comments: true
    open-in-view: false

#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.type: trace